name: Terraform CI-CD

on:
  pull_request:
    branches:
      - main
      - feature/action

  push:
    branches:
      - main
      - feature/action

permissions:
  contents: read

jobs:

  terraform-plan:
    name: Terraform Plan
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform init
          terraform fmt -check -recursive
          terraform validate
          terraform plan -var-file="jio.tfvars"


  terraform-apply:
    name: Terraform Apply
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform plan -var-file="jio.tfvars" -out=tfplan
          terraform apply -auto-approve tfplan